debug: true
server:
  port: 8787

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  file: C:/Apigee/micro-services/Work/Azure/pologs/plm-webportal-ms.log
  #${HOME}\site\wwwroot\pologs\web-portal.log